# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('text', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DTC',
            fields=[
                ('bmw_code', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('causes', models.ManyToManyField(to='nd.Cause')),
            ],
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('text', models.CharField(max_length=400, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=200)),
                ('page', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceFix',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='dtc',
            name='fixes',
            field=models.ManyToManyField(to='nd.Fix'),
        ),
    ]
