# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DTC',
            fields=[
                ('bmw_code', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fault', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('causes', models.ManyToManyField(to='nd.Cause')),
            ],
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nd.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(db_index=True)),
                ('text', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceFix',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=200)),
                ('page', models.IntegerField(db_index=True)),
                ('text', models.CharField(db_index=True, max_length=2000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together=set([('filename', 'page', 'text')]),
        ),
        migrations.AddField(
            model_name='phrase',
            name='sentences',
            field=models.ManyToManyField(related_name='phrases', to='nd.Sentence'),
        ),
        migrations.AddField(
            model_name='dtc',
            name='fixes',
            field=models.ManyToManyField(to='nd.Fix'),
        ),
        migrations.AlterUniqueTogether(
            name='partlabel',
            unique_together=set([('label', 'part', 'text')]),
        ),
    ]
