# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('text', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DTC',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('causes', models.ManyToManyField(to='nd.Cause')),
            ],
        ),
    ]
