# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nd', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partlabel',
            unique_together=set([('label', 'part', 'text')]),
        ),
    ]
